### ISSUE TITLE
break option should leave a space above

### ISSUE THREAD

**Issue by mslinn** [mslinn/jekyll_quote#1]
Add a CSS class called `quoteBreak`, and add the class to the generated tag.
```css
quoteBreak { 
  margin-top: 1em; 
}
```
